### PR TITLE
Fix for GitLab datetime formats

### PR DESCRIPTION
**Pull request by nkottary**
New version of GitLab uses multiple datetime formats.

This requires https://github.com/quinnj/JSON2.jl/pull/32

### CODE REVIEW

**Comment by christopher-dG** [comment]
probably related: #9

**Comment by aviks** [comment]
This fix is pending an open PR to JSON2. 

@christopher-dG  Is there a particular reason for using JSON2 on this package? Do you need some of the auto-serialisation features of that package? I ask since JSON and JSON3 seem to be much more actively maintained?

**Comment by christopher-dG** [comment]
The serialization features were exactly what I needed (and JSON did not have that). JSON3 was not a thing when I wrote this package.

I've invited @nkottary and @oxinabox to be collaborators on this repo, since I don't really have much interest in maintaining it these days. You guys may do as you please with these PRs (if you have the time and desire to do so) 🙂. 
If you want to migrate to JSON3, I'm all for it! 
It might also be worth looking into merged the `cdg/02` branch, which changes the way that requests/responses work to be a bit more Julian.

**Comment by oxinabox** [comment]
Maybe this Repo should be transferred to JuliaRegistries (since it is a depenendency of things there) or JuliaCI ?

**Pull request merged**
